/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simple.kasir;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static simple.kasir.Koneksi.getConnection;

/**
 *
 * @author cincun
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    private DefaultTableModel TabModel;
    String id;
    String nama;
    String harga;
    long totHarga;

    public View() {
        initComponents();
//        Object[] Baris = {"Id", "Nama", "Harga"};
//        TabModel = new DefaultTableModel(null, Baris);
//        jTable1.setModel(TabModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tambahBarang = new javax.swing.JButton();
        hapusBarang = new javax.swing.JButton();
        editBarang = new javax.swing.JButton();
        jTextNamaTambah = new javax.swing.JTextField();
        jTextHargaTambah = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        keluar = new javax.swing.JButton();
        testDatabase = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tampilData = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        inputDataBarang = new javax.swing.JButton();
        hapusInputBarang = new javax.swing.JButton();
        totalHarga = new javax.swing.JButton();
        hapusSemua = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1049, 693));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NAMA", "HARGA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 210, 1000, 450);

        tambahBarang.setText("TAMBAH");
        tambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBarangActionPerformed(evt);
            }
        });
        jPanel1.add(tambahBarang);
        tambahBarang.setBounds(890, 30, 110, 25);

        hapusBarang.setText("HAPUS");
        hapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBarangActionPerformed(evt);
            }
        });
        jPanel1.add(hapusBarang);
        hapusBarang.setBounds(890, 110, 110, 25);

        editBarang.setText("GANTI");
        editBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBarangActionPerformed(evt);
            }
        });
        jPanel1.add(editBarang);
        editBarang.setBounds(890, 70, 110, 25);

        jTextNamaTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNamaTambahActionPerformed(evt);
            }
        });
        jPanel1.add(jTextNamaTambah);
        jTextNamaTambah.setBounds(510, 30, 180, 30);
        jPanel1.add(jTextHargaTambah);
        jTextHargaTambah.setBounds(700, 30, 160, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(440, 70, 60, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(510, 70, 180, 30);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(700, 70, 160, 30);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(800, 110, 60, 30);

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar);
        keluar.setBounds(20, 100, 110, 25);

        testDatabase.setText("TEST DATABASE");
        testDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testDatabaseActionPerformed(evt);
            }
        });
        jPanel1.add(testDatabase);
        testDatabase.setBounds(20, 20, 170, 25);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 20, 160, 30);

        tampilData.setText("TAMPIL DATA");
        tampilData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilDataActionPerformed(evt);
            }
        });
        jPanel1.add(tampilData);
        tampilData.setBounds(20, 60, 150, 25);

        jLabel3.setFont(new java.awt.Font("Abyssinica SIL", 1, 12)); // NOI18N
        jLabel3.setText("Id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(800, 100, 20, 13);

        jLabel5.setFont(new java.awt.Font("Abyssinica SIL", 1, 12)); // NOI18N
        jLabel5.setText("Nama");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(510, 60, 50, 10);

        jLabel6.setFont(new java.awt.Font("Abyssinica SIL", 1, 12)); // NOI18N
        jLabel6.setText("Harga");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(700, 50, 50, 30);

        jLabel8.setFont(new java.awt.Font("Abyssinica SIL", 1, 12)); // NOI18N
        jLabel8.setText("Id");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 60, 40, 13);

        jLabel7.setFont(new java.awt.Font("Abyssinica SIL", 1, 12)); // NOI18N
        jLabel7.setText("Nama");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(510, 20, 50, 10);

        jLabel9.setFont(new java.awt.Font("Abyssinica SIL", 1, 12)); // NOI18N
        jLabel9.setText("Harga");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(700, 10, 50, 30);

        jLabel14.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("AZIRAF MART");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(250, 110, 310, 70);

        jTabbedPane1.addTab("ADMIN", jPanel1);

        jPanel2.setLayout(null);

        jScrollPane3.setBackground(new java.awt.Color(204, 0, 204));

        jTable3.setAutoCreateRowSorter(true);
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NAMA", "JUMLAH", "HARGA"
            }
        ));
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 130, 1000, 410);
        jPanel2.add(jTextField8);
        jTextField8.setBounds(110, 20, 60, 30);

        inputDataBarang.setText("TAMBAHKAN");
        inputDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDataBarangActionPerformed(evt);
            }
        });
        jPanel2.add(inputDataBarang);
        inputDataBarang.setBounds(180, 60, 130, 30);

        hapusInputBarang.setText("HAPUS");
        hapusInputBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusInputBarangActionPerformed(evt);
            }
        });
        jPanel2.add(hapusInputBarang);
        hapusInputBarang.setBounds(880, 70, 130, 30);

        totalHarga.setText("TOTAL");
        totalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalHargaActionPerformed(evt);
            }
        });
        jPanel2.add(totalHarga);
        totalHarga.setBounds(650, 540, 150, 25);

        hapusSemua.setText("HAPUS SEMUA");
        hapusSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusSemuaActionPerformed(evt);
            }
        });
        jPanel2.add(hapusSemua);
        hapusSemua.setBounds(650, 580, 150, 25);
        jPanel2.add(jTextField9);
        jTextField9.setBounds(820, 70, 50, 30);

        jLabel1.setText("RP.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(810, 540, 30, 30);

        jLabel2.setText("---------------------");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(850, 540, 150, 30);

        jLabel10.setText("JUMLAH");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 60, 90, 30);

        jLabel11.setText("ID BARANG");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(730, 70, 90, 30);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(110, 60, 60, 30);

        jLabel12.setText("ID BARANG");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 20, 90, 30);

        jLabel13.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("AZIRAF MART");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(370, 20, 310, 70);

        jTabbedPane1.addTab("KASIR", jPanel2);
        jTabbedPane1.addTab("history", jPanel3);
        jTabbedPane1.addTab("tab4", jPanel4);
        jTabbedPane1.addTab("tab5", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1030, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusSemuaActionPerformed
        clearTable(jTable3);
        j = 0;
    }//GEN-LAST:event_hapusSemuaActionPerformed

    private void totalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalHargaActionPerformed
        for (int i = 0; i < jTable3.getRowCount(); i++) {
            String harga = (String) jTable3.getValueAt(i, 3);
            String jum = (String) jTable3.getValueAt(i, 2);
            System.out.println("Harga : " + harga);
            System.out.println("Jumlah: " + jum);
            if ((harga != null) && (jum != null) && (harga != "") && (jum != "")) {
                long hargaBarang = (long) Long.parseLong(harga);
                long jumlah = (long) Long.parseLong(jum);
                totHarga = totHarga + hargaBarang * jumlah;
            }
//            else{
//                JOptionPane.showMessageDialog(null, "Kosong!");
//            }
        }

        String totalHarga = Long.toString(totHarga);
        jLabel2.setText(totalHarga);
    }//GEN-LAST:event_totalHargaActionPerformed

    private void hapusInputBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusInputBarangActionPerformed
        String id1 = (String) jTextField9.getText();
        System.out.println(id1);
        boolean status = true;
        if (cekAngka(id1) && id1 != "" && id1 != null) {
            for (int i = 0; i < jTable3.getRowCount(); i++) {
                String id2 = (String) jTable3.getValueAt(i, 0);
                if (id1.equals(id2)) {
                    jTable3.setValueAt("", i, 0);
                    jTable3.setValueAt("", i, 1);
                    jTable3.setValueAt("", i, 2);
                    jTable3.setValueAt("", i, 3);
                    jTextField9.setText("");
                    status = false;
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak boleh kosong dan harus angka!");
        }
        if (status) {
            JOptionPane.showMessageDialog(null, "Tidak ada id cocok !");

        }
    }//GEN-LAST:event_hapusInputBarangActionPerformed

    private void inputDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDataBarangActionPerformed
        DatabaseMinikasir db = new DatabaseMinikasir();
        String id2 = (String) jTextField8.getText();
        String jumlah = jTextField1.getText();
        boolean status = true;
        if (cekAngka(id2) && cekAngka(jumlah) && id != "" && jumlah != "") {
            try {
                ResultSet rs = db.getData("select * from Barang");
                while (rs.next()) {
                    id = (String) rs.getString("id");
                    System.out.println(id);
                    if (id2.equals(id)) {
                        nama = rs.getString("nama");
                        harga = rs.getString("harga");
                        jTable3.setValueAt(id, j, 0);
                        jTable3.setValueAt(nama, j, 1);
                        jTable3.setValueAt(jumlah, j, 2);
                        jTable3.setValueAt(harga, j, 3);
                        jTextField8.setText("");
                        jTextField1.setText("");
                        System.out.println(id + nama + harga);
                        status = false;
                        j++;
                    }
                }
                if (status) {
                    JOptionPane.showMessageDialog(null, "Tidak ada ID yang cocok !");
                }
                rs.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            if (id2 == "" || jumlah == "" || id2 == null || jumlah == null) {
                JOptionPane.showMessageDialog(null, "Masukan tidak boleh kosong !");
            }
            System.out.println("ID     :" + id2);
            System.out.println("Jumlah :" + jumlah);
            if (!cekAngka(id2) || !cekAngka(jumlah)) {
                JOptionPane.showMessageDialog(null, "Masukan salah, tidak boleh kosong dan harus angka !");
            }
        }
    }//GEN-LAST:event_inputDataBarangActionPerformed

    private void tampilDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilDataActionPerformed
        showBarang();
    }//GEN-LAST:event_tampilDataActionPerformed

    private void testDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testDatabaseActionPerformed
        try {
            getConnection();
            System.out.println("Koneksi Berhasil");
            jLabel4.setText("Database Connect");
        } catch (SQLException ex) {
            System.err.println("Koneksi Gagal");
            jLabel4.setText("Database Failed");
        }
    }//GEN-LAST:event_testDatabaseActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void jTextNamaTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNamaTambahActionPerformed

    }//GEN-LAST:event_jTextNamaTambahActionPerformed

    private void editBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBarangActionPerformed
        id = jTextField4.getText();
        nama = jTextField5.getText();
        harga = jTextField6.getText();

        if ((nama == "") || (harga == "")) {
            JOptionPane.showMessageDialog(null, "Tidak boleh kosong !");
        } else if (!cekAngka(id)) {
            JOptionPane.showMessageDialog(null, "ID harus angka !");
        } else if ((cekAngka(nama))) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong dan harus huruf !");
        } else if ((!cekAngka(harga))) {
            JOptionPane.showMessageDialog(null, "Harga harus angka !");
        } else if ((nama != "") && harga != "" && id != "" && cekAngka(id) && (cekAngka(harga)) && !cekAngka(nama)) {
            Barang barang = new Barang(nama, harga, id);
            barang.updateBarang();
            showBarang();
            if (barang.ismasuk) {
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada id cocok !");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan !");
        }
    }//GEN-LAST:event_editBarangActionPerformed

    private void hapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBarangActionPerformed
        id = jTextField7.getText();
        Barang barang = new Barang();
        barang.setId(id);
        barang.deleteBarang();
        showBarang();
        if (barang.ismasuk) {
            jTextField7.setText("");
        }
    }//GEN-LAST:event_hapusBarangActionPerformed

    private void tambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBarangActionPerformed
        nama = jTextNamaTambah.getText();
        harga = jTextHargaTambah.getText();

        Barang barang = new Barang(nama, harga, id);

        if ((nama != "") && harga != "" && (cekAngka(harga)) && !cekAngka(nama)) {
            barang.insertBarang();
            //        String[] dataField = {id, nama, harga};
            //        TabModel.addRow(dataField);
            showBarang();
            System.out.println(nama);
            System.out.println(harga);
            System.out.println(id);
            if (barang.ismasuk) {
                jTextNamaTambah.setText("");
                jTextHargaTambah.setText("");
            }
        } else if ((nama == "") || (harga == "")) {
            JOptionPane.showMessageDialog(null, "Tidak boleh kosong !");
        } else if ((cekAngka(nama))) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh angka !");
        } else if ((!cekAngka(harga))) {
            JOptionPane.showMessageDialog(null, "Harga harus angka !");
        } else {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan !");
        }
    }//GEN-LAST:event_tambahBarangActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed
    int j;
    /**
     * @param args the command line arguments
     */
    public void showBarang() {
        DatabaseMinikasir db = new DatabaseMinikasir();

        try {
            int i = 0;
            clearTable(jTable1);
            ResultSet rs = db.getData("select * from Barang");
            while (rs.next()) {
                id = rs.getString("id");
                nama = rs.getString("nama");
                harga = rs.getString("harga");

                jTable1.setValueAt(id, i, 0);
                jTable1.setValueAt(nama, i, 1);
                jTable1.setValueAt(harga, i, 2);
                System.out.println(id + nama + harga);
                i++;
            }
            rs.close();
        } catch (Exception e) {
        }
    }

    public static void clearTable(final JTable table) {
        for (int i = 0; i < table.getRowCount(); i++) {
            for (int j = 0; j < table.getColumnCount(); j++) {
                table.setValueAt("", i, j);
            }
        }
    }

    public boolean cekAngka(String masukan) {
        boolean isangka = true; //Inisialisasi pembanding
        try {
            long a = Long.parseLong(masukan);
            /**
             * Jika perintah diatas salah dan error maka akan ditampung oleh
             * Catch(Exception e)
             */
        } catch (Exception e) {
            isangka = false;
        }

        return isangka;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (Stringroduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GRK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editBarang;
    private javax.swing.JButton hapusBarang;
    private javax.swing.JButton hapusInputBarang;
    private javax.swing.JButton hapusSemua;
    private javax.swing.JButton inputDataBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextHargaTambah;
    private javax.swing.JTextField jTextNamaTambah;
    private javax.swing.JButton keluar;
    private javax.swing.JButton tambahBarang;
    private javax.swing.JButton tampilData;
    private javax.swing.JButton testDatabase;
    private javax.swing.JButton totalHarga;
    // End of variables declaration//GEN-END:variables
}
